# Generated by Django 2.0 on 2018-02-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('score', models.IntegerField()),
                ('violations', models.IntegerField()),
                ('sentiment', models.FloatField()),
                ('satisfaction', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(max_length=32)),
                ('score', models.FloatField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.Call')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_employee', models.BooleanField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.Call')),
            ],
        ),
    ]
