# Generated by Django 2.0 on 2018-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
