# Generated by Django 2.0 on 2018-02-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20180210_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='tone',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tones', to='call.Call'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='call.Call'),
        ),
    ]
